[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=50.0.0", "wheel"]

[tool.pytest.ini_options]
addopts = "-p no:faulthandler -r s --cov=./src/r5py --cov-append --cov-report term-missing --cov-report xml"
pythonpath = ["src"]
testpaths = ["tests"]

[tool.coverage.run]
omit = ["tests/*"]
