name: r5py
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - accessible-pygments=0.0.5
  - affine=2.4.0
  - alabaster=1.0.0
  - alsa-lib=1.2.13
  - anyio=4.8.0
  - aom=3.9.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=25.1.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - black=25.1.0
  - black-jupyter=25.1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - click-plugins=1.1.1
  - cligj=0.7.2
  - codecov=2.1.13
  - colorama=0.4.6
  - comm=0.2.2
  - configargparse=1.7
  - contextily=1.6.2
  - contourpy=1.3.1
  - coverage=7.6.12
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.13
  - decorator=5.2.1
  - defusedxml=0.7.1
  - docutils=0.21.2
  - double-conversion=3.3.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - filelock=3.17.0
  - folium=0.19.5
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - geographiclib=2.0
  - geohexgrid=2.1.1
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geopy=2.4.1
  - geos=3.13.1
  - geotiff=1.7.4
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glog=0.7.1
  - graphite2=1.3.13
  - greenlet=3.1.1
  - h11=0.14.0
  - h2=4.2.0
  - h3=4.2.0
  - harfbuzz=10.4.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpype1=1.5.2
  - json-c=0.18
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-cache=1.0.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab-myst=2.4.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupytext=1.16.7
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - latexcodec=2.0.1
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarchive=3.7.7
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libavif16=1.2.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.12.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgdal-core=3.10.2
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.67.1
  - libheif=1.19.7
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libparquet=19.0.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.4
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialindex=2.1.0
  - libspatialite=5.1.0
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.6
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.8.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - mercantile=1.2.1
  - minizip=4.0.7
  - mistune=3.1.2
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - myst-nb=1.2.0
  - myst-parser=4.0.1
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nbsphinx=0.9.7
  - nbstripout=0.8.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - notebook-shim=0.2.4
  - numpy=2.2.3
  - openjdk=23.0.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - orc=2.1.1
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=3.6.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathspec=0.12.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - proj=9.5.1
  - prometheus-cpp=1.3.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pybtex=0.24.0
  - pybtex-docutils=1.0.3
  - pycparser=2.22
  - pydata-sphinx-theme=0.15.4
  - pygments=2.19.1
  - pyogrio=0.10.0
  - pyparsing=3.2.1
  - pyproj=3.7.1
  - pyside6=6.8.2
  - pysocks=1.7.1
  - pytest=8.3.5
  - pytest-asyncio=0.25.3
  - pytest-cov=6.0.0
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.1
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - qt6-main=6.8.2
  - r5py=1.0.0
  - r5py.sampledata.helsinki=0.1.2
  - r5py.sampledata.sao_paulo=0.1.2
  - rasterio=1.4.3
  - rav1e=0.6.6
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - roman-numerals-py=3.1.0
  - rpds-py=0.23.1
  - rtree=1.4.0
  - s2n=1.5.11
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - send2trash=1.8.3
  - setuptools=75.8.2
  - shapely=2.0.7
  - simplification=0.7.13
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.1
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - soupsieve=2.5
  - sphinx=8.2.3
  - sphinx-book-theme=1.1.4
  - sphinx-design=0.6.1
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-bibtex=2.6.3
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlalchemy=2.0.38
  - sqlite=3.49.1
  - stack_data=0.6.3
  - svt-av1=3.0.0
  - tabulate=0.9.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenize-rt=6.1.0
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.3.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xyzservices=2025.1.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - pybtex-apa7-style==0.1.3
      - pytest-lazy-fixtures==1.1.2
