# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Update binder environment
on:
  push:
    paths:
      - ci/*.yaml
  pull_request:
    paths:
      - ci/*.yaml
  workflow_call:

jobs:
  update-binder-env:
    name: Update binder environment
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: conda-incubator/setup-miniconda@v3

      - run: |
          conda env create --file=ci/r5py_dev.yaml 
          conda env export --no-builds --name r5py | grep -Ev '^prefix:' > .binder/environment.yml

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit .binder/environment.yml -m "ðŸ¤–: updated binder environment"
          git push
