# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Create a release and deploy to PyPi whenever a protected tag (v0.0.0) is created

on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    name: Build wheel(s) and packages
    needs: test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python_version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
      - run: python -m pip install build
      - run: python -m build .
      - uses: actions/upload-artifact@v4
        with:
          name: "package"
          path: dist/*.*
          overwrite: true

  merge-into-stable:
    name: Update stable branch to point to this release
    runs-on: ubuntu-latest
    needs: [build]
    if: "!contains(github.ref, 'dev')"
    permissions: write-all
    steps:
      - name: Clone repository, check-out stable
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: stable
      - name: Merge tag into stable
        run: |
          TAG="${{github.ref}}"  # /ref/tags/v0.0.0
          git merge "${TAG:10}"
          git push

  deploy:
    name: Upload built package to PyPi
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: pypi
      url: https://pypi.org/p/r5py
    permissions:
      id-token: write
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: "package"
          path: dist/
      - name: Upload package to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true

  release:
    name: Create a new release
    runs-on: ubuntu-latest
    needs: [deploy]
    if: "!contains(github.ref, 'dev')"
    permissions:
      contents: write
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: "package"
          path: dist/
      - name: Create release and upload package
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

  prerelease:
    name: Create a new pre-release
    runs-on: ubuntu-latest
    needs: [deploy]
    if: contains(github.ref, 'dev')
    permissions:
      contents: write
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: "package"
          path: dist/
      - name: Create release and upload package
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          prerelease: true
